apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: quickstart-image
          ports:
            - containerPort: 8080
