steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/gke-cicd-422619/demo/quickstart-image', './app1' ]
  id: 'Build Docker Image 1'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/gke-cicd-422619/demo/quickstart-image' ]
  id: 'Push Docker Image 1'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east4-docker.pkg.dev/gke-cicd-422619/gke-repo/quickstart-image', './app1' ]
  id: 'Build Docker Image 2'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east4-docker.pkg.dev/gke-cicd-422619/gke-repo/quickstart-image' ]
  id: 'Push Docker Image 2'

options:
  logging: CLOUD_LOGGING_ONLY
