steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/devops-v4-e2/gke-repo/quickstart-image', './app1' ]
  id: 'Build Docker Image'

  # images:
  # - 'us-central1-docker.pkg.dev/<your_project_id>/gke-repo/quickstart-image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/devops-v4-e2/gke-repo/quickstart-image' ]
  id: 'Push Docker Image'




- name: 'google/cloud-sdk:latest'
  args:
    - -c
    - kubectl apply -f kubernetes/app1.yaml
    #gcloud deploy apply --file kubernetes/app1.yaml --region=us-central1-f
    #gcloud deploy apply --file deploy/dev.yaml --region=us-central1
    #gcloud deploy releases create 'app-release-${SHORT_SHA}' --delivery-pipeline=demo-btdnncd --region=us-central1 --skaffold-file=skaffold.yaml


options:
  logging: CLOUD_LOGGING_ONLY
