---
apiVersion: v1
kind: ConfigMap
metadata:
  name: datasources
  namespace: monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: PrometheusUI
      type: prometheus
      url: http://frontend.monitoring:8080
      isDefault: true
      jsonData:
        manageAlerts: false
        timeout: 60
