apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      serviceAccountName: service-account
      containers:
        - name: my-container
          image: gcr.io/gke-cicd-422619/myapp1:v1.0
          ports:
            - containerPort: 8080
