---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-ui
  namespace: monitoring
  annotations:
    iam.gke.io/gcp-service-account: prometheus-ui@gke-cicd-422619.iam.gserviceaccount.com 
