---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: service-account
      containers:
      - name: frontend
        image: quickstart-image
        args:
        - --web.listen-address=:8080
        - --query.project-id=gke-cicd-422619 
        ports:
        - name: web
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /-/ready
            port: web
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: web
